### ISSUE TITLE
Engine menu - OWL and Rules

### ISSUE THREAD

**Issue by FabienGandon** [Wimmics/corese#110]
Hello,

Using the toy datasets humans_data.ttl and human_schema.ttl I have a strange behaviour when I add the following definition to the schema:

```
:hasSibling a owl:ObjectProperty ;
    rdfs:label "has for sibling"@en, "a pour frère ou sœur"@fr ;
    rdfs:comment "a relative that shares at least one parent with the subject."@en,
                 "relation avec quelqu'un ayant les mêmes parents."@fr ;
    rdfs:domain :Animal ;
    rdfs:range  :Animal ;
	owl:propertyChainAxiom ( :hasParent :hasChild ) .
```

If I select OWL RL and OWL RL extended and run the rules I see the new hasSibling links and if I reload and run the rules again I don't have them anymore.

**Comment by ocorby** [comment]
Hello, 
There is aka bug in the gui checkbox, you need to unselect and then select again OWL RL Extended (in the version from github) 
We will clean that. 
Olivier

**Comment by FabienGandon** [comment]
If fact the behaviour is more complex:
- I (re)load the data and the schema : no inferences even if OWL RL was selected before (re)loading)
- I unselect-reselect OWL RL I get some inferences (eg I get the ancestors but not the siblings)
- I unselect-reselect OWL RL a second time I get more inferences (eg I get the siblings)

**Comment by remiceres** [comment]
Hello Fabien,

We think we have corrected this bug with @ocorby . There were 2 problems:

- **Display problem:** The status of the checkboxes was inconsistent because it was not updated during the reload.
- **Rule engine problem :** The rule engine was implementing optimizations that were incompatible with the `owl:propertyChainAxiom` rule.

Corese-GUI fix: <http://files.inria.fr/corese/distrib/beta/corese-gui-fix-110.jar>

I am waiting for confirmation that everything is working on your side before closing this issue.

**Comment by FabienGandon** [comment]
I ran the test and it works for me.
I will have to check the rest of the lab session.
Thanks
