### ISSUE TITLE
Corese server: Loop feature is blocking the execution of other queries in paralell

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/corese#117]
When the Corese server handles a federated query using the loop feature, it pauses all other queries once it has received its first response for the federated query.

Attached is a basic NodeJS script reproducing what I have observed in my program.
The script sends 20 `ASK { ?s ?p ?o}` queries before and after a complex query (it counts all the unique classes in DBpedia).
The execution of the 40 resulting simple queries is paused in the middle when Corese starts to loop for the resolution of the complex query.

On a computer with Node installed and an instance of Corese server with access to DBpedia, unzip the file in a folder. In a terminal in this folder,  the script is installed with `npm i` and is run with `npm run run`
[CoreseBugRepro.zip](https://github.com/Wimmics/corese/files/10229814/CoreseBugRepro.zip)

**Comment by remiceres** [comment]
Hello Pierre,

Thank you for your script. After researching, I think the problem is not with threads or the loop feature.

I think the problem is caused by the lock system between write and read queries.

## Your Script

Your script sends 20 **read** queries:

```sparql
ASK {
    SERVICE <http://dbpedia.org/sparql> {
        ?s ?p ?o
    }
}
```

Next, 1 big **write** query:

```sparql
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX earl: <http://www.w3.org/ns/earl#>
PREFIX kgi: <http://ns.inria.fr/kg/index#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
INSERT {
    <http://e.g/Dataset> void:classes ?count .
}
WHERE {
    SELECT (COUNT(?c) AS ?count) {
        SERVICE <http://dbpedia.org/sparql?mode=loop&limit=1000&timeout=10000> {
            SELECT DISTINCT ?c
            WHERE {
                ?s a ?c .
                FILTER(isIRI(?c))
            }
        }
    }
}
```

And, 20 **read** queries again:

```sparql
ASK {
    SERVICE <http://dbpedia.org/sparql> {
        ?s ?p ?o
    }
}
```

> I added a delay of 100ms between each query sent in order to be sure the Corese server receives queries in the same order ([script with delay.zip](https://github.com/Wimmics/corese/files/10280602/script.with.delay.zip)).

## Corese server behavior

1. Answer the first 20 read queries.
1. Only after the first 20 read queries are over, answer the big write query.
1. Only after the big write query is over, answer the 20 first read queries.

## Problem description

Here, the problem is caused by the lock system between read and write queries.

There are two types of queries: read (that do not modify the graph) and write (that modify the graph).

When Corese receives a read query, the graph is locked in read.

A read lock:

- Allows for parallel reading queries.
- Blocks parallel write queries.

When Corese receives a write query, the graph is locked in write.

A write lock:

- Blocks parallel reading queries.
- Blocks parallel write queries.

Here's what happens:

Corese processes query in the same order that it receives them.

1. Corese receives the first 20 read queries and sets a read lock on the graph. The first 20 queries can be processed in parallel because they are all read queries. The write queries are locked.
2. When the first 20 read queries are completed, the read lock is removed. Corese sets a write lock and starts processing the big write query. All other read and write queries are locked.
3. When the big query is done, the write lock is removed and Corese can process the last 20 read queries.

> For example, if you replace the big write query with a big read query, there is no problem.

## Possible solutions

- You can have two Corese server instances, one for service clauses and a second for write queries..

- In this case, your read queries don't read information from the Corese graph, but just query an external SPARQL endpoint with service clauses. I think we can change Corese's behavior so that if queries don't read information in the Corese graph, they are not blocked by read or write locks. What do you think about this solution @ocorby ?

**Comment by ocorby** [comment]
Bonjour, 

Au lieu de : 
ASK { SERVICE <http://dbpedia.org/sparql> { ?s ?p ?o }
} 

Il faudrait écrire : 
ASK { SERVICE <http://dbpedia.org/sparql> { 
select * where { ?s ?p ?o 
} limit 1 }
} 

En ce qui concerne le fait de ne pas mettre de lock en cas de requête read et service only, 
je trouve ça un peu dangereux, 
ça fait une exception qui risque de poser problème pcq toute la logique de conception de corese est basée 
sur ces locks read/write. 

Une autre possibilité serait d'envoyer une requête read service only 
directement au endpoint distant plutôt que de passer par corese. 

Bonnes fêtes. 

Olivier
