### ISSUE TITLE
How to use the extended SPARQL construct

### ISSUE THREAD

**Issue by szarnyasg** [Wimmics/corese#4]
Hi,

I managed to get Corese working with basic SPARQL queries. I have a couple of questions about the extended SPARQL language:

1. I'd like to use the `param[...]` construct described in the paper [Analysis of a Real Online Social Network Using Semantic Web Frameworks](http://link.springer.com/chapter/10.1007/978-3-642-04930-9_12). Does this work in the current version of Corese? Or do I have to "simulate" this by generating the queries for all parameters?

2. I've found `group by any` queries in the tests ([1](https://github.com/Wimmics/corese/blob/master/kgengine/src/test/java/kgraph/TestQuery.java), [2](https://github.com/Wimmics/corese/blob/master/kgengine/src/test/java/junit/TestQuery1.java)), but I couldn't get it working:

  ```
  PREFIX base: <http://www.semanticweb.org/ontologies/2015/trainbenchmark#> 
  select ?x ?y 
  where {
    ?x base:follows ?y
  }
  group by any
  ```

  This throws an exception:

  ```
  ERROR 2015-12-05 19:44:47,855 [562367320@qtp-354432491-19] (SPARQLRestAPI.java:398) - Error while querying the remote KGRAM engine
  ```

  (Without the `group by any` line, it's fine).

3. Is there a more up-to-date version of this [documentation](http://www-sop.inria.fr/acacia/soft/corese/manual/) somewhere?

Thanks,
Gabor

**Comment by ocorby** [comment]
Hi,

Unfortunately these features are not available anymore.

There is a new way to perform these types of computing. It consists in 
associating a plugin to the SPARQL interpreter in such a way that :
each time a solution of  the query is found or a property path is 
identified, a plugin callback function is called in order to perform 
specific processing, e.g. network analysis operation.

The plugin must implement the ResultListener interface 
(fr.inria.edelweiss.kgram.event ; kgram project)

The main functions to be implemented are :


public boolean process(Path path)

public boolean process(Environment env)


Best regards


Olivier Corby

**Comment by szarnyasg** [comment]
Thanks, I'll look into the Java API.
